"""add variation fields to question model

Revision ID: 27e2fdc749d8
Revises: 
Create Date: 2025-03-26 12:59:11.314994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e2fdc749d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_variation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('original_question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'question', ['original_question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_question_id')
        batch_op.drop_column('is_variation')

    # ### end Alembic commands ###
