"""add marks and variation fields to question model

Revision ID: ae0765a64b4a
Revises: 27e2fdc749d8
Create Date: 2025-03-26 13:11:27.592210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0765a64b4a'
down_revision = '27e2fdc749d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solution_steps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('solution_steps')
        batch_op.drop_column('context')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('order')
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
